In [ ]:
import os
import sqlite3
import pandas as pd
from pathlib import Path

# Use a file-based SQLite DB inside Data/Raw
db_path = r"C:\Users\Scalefusion admin\Desktop\proj_ipl\Data\Raw\ipl.db"
Path(os.path.dirname(db_path)).mkdir(parents=True, exist_ok=True)
con = sqlite3.connect(db_path)

def q(sql):
    return pd.read_sql_query(sql, con)

OperationalError: unable to open database file

In [16]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [17]:
run_sql_file(r"C:\Users\Scalefusion admin\Desktop\proj_ipl\sql\01_nulls_and_blanks.sql")

NameError: name 'con' is not defined

In [ ]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\01_nulls_and_blanks.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\01_nulls_and_blanks.sql

In [ ]:
q("""select count(*) as blank_before
from players
where trim(field_pos)='';""")

   blank_before
0           612

In [ ]:
q("""select count(*) as null_after
from v_players_clean
where field_pos_clean is null;""")

   null_after
0         700

In [ ]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\02_merge_categories.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\02_merge_categories.sql

In [ ]:
q("""select  distinct team_name
from teams
order by team_name""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [ ]:
q("""select distinct team_name_clean
 from v_teams_clean
 order by team_name_clean;""")

                team_name_clean
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14          Sunrisers Hyderabad

In [ ]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\03_venue_names.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\03_venue_names.sql

In [ ]:
q("""select venue, count(*) as matches
from matches
where venue In('Wankhede Stadium', 'Wankhede Stadium, Mumbai')
group by venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [ ]:
q("""select venue, count(*) as matches
from matches
group by venue
order by matches desc
limit 10;""")

                                       venue  matches
0                               Eden Gardens       77
1                           Wankhede Stadium       73
2                      M Chinnaswamy Stadium       65
3                           Feroz Shah Kotla       60
4                   Wankhede Stadium, Mumbai       57
5  Rajiv Gandhi International Stadium, Uppal       49
6            MA Chidambaram Stadium, Chepauk       48
7                     Sawai Mansingh Stadium       47
8        Dubai International Cricket Stadium       46
9   MA Chidambaram Stadium, Chepauk, Chennai       38

In [ ]:
q(""" select venue_clean, COUNT(*) AS matches
from v_matches_venue
GROUP BY venue_clean
order by matches desc limit 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1               M Chinnaswamy Stadium      104
2                        Eden Gardens      104
3              MA Chidambaram Stadium       95
4  Rajiv Gandhi International Stadium       87

In [ ]:
q("""select count(*), venue, city
from venues
group by venue
order by count(*)desc
limit 10;""")

   count(*)                                              venue       city
0         2                            Sharjah Cricket Stadium       None
1         2  Maharaja Yadavindra Singh International Cricke...     Mohali
2         2                Dubai International Cricket Stadium       None
3         2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4         1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi
5         1                           Wankhede Stadium, Mumbai     Mumbai
6         1                                   Wankhede Stadium     Mumbai
7         1       Vidarbha Cricket Association Stadium, Jamtha     Nagpur
8         1                                    SuperSport Park  Centurion
9         1                         Subrata Roy Sahara Stadium       Pune

In [ ]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\04_dedupe_venues.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\04_dedupe_venues.sql

In [ ]:
q("""select count(*) as rows, count(distinct venue)as names
from v_venues_clean;""")

   rows  names
0    59     59

In [ ]:
q("""select count(*), venue, city
from v_venues_clean
group by venue
order by count(*)desc
limit 10;""")

   count(*)                                             venue            city
0         1                  Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1         1                          Wankhede Stadium, Mumbai          Mumbai
2         1                                  Wankhede Stadium          Mumbai
3         1      Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4         1                                   SuperSport Park       Centurion
5         1                        Subrata Roy Sahara Stadium            Pune
6         1                                  St George's Park  Port Elizabeth
7         1                              Sheikh Zayed Stadium       Abu Dhabi
8         1                           Sharjah Cricket Stadium         Sharjah
9         1  Shaheed Veer Narayan Singh International Stadium          Raipur

In [ ]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\05_city_fallback.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\05_city_fallback.sql

In [ ]:
q("""select city_clean from v_city_clean
where city_clean is null;""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [ ]:
q("""select city_clean from v_city_clean
where city_clean = 'UNKNOWN';""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [ ]:
q(""" SELECT city_clean FROM v_city_clean
WHERE city_clean IN('UNKNOWN');""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [ ]:
q(""" SELECT city_clean FROM v_city_clean
LIMIT 5;""")

  city_clean
0  Bangalore
1  Hyderabad
2       Pune
3     Rajkot
4     Indore

In [ ]:
q(""" select season,
         count(*) as matches
from matches
where season ='2020/21'
group by season;""")

    season  matches
0  2020/21       60

In [ ]:
run_sql_file(
    r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\06_season_year.sql"
)

q("""
SELECT DISTINCT season, season_year
FROM v_season
WHERE season = '2020/21';
""")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\06_season_year.sql

    season  season_year
0  2020/21         2020

In [ ]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\08_matches_clean.sql")

ran C:\Users\muham\OneDrive\Desktop\Proj_3.1\sql\08_matches_clean.sql

In [ ]:
q(""" select  * from matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field
...,...,...,...,...,...,...,...,...
1063,1529279,Sawai Mansingh Stadium,Jaipur,2026,win,Sunrisers Hyderabad,Ishan Kishan,field
1064,1529280,MA Chidambaram Stadium,Chennai,2026,win,Gujarat Titans,K Rabada,field
1065,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field
1066,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat
1067,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat